### ISSUE TITLE
Increase max_stack_height value after fixing stack limiter bug in casper-wasm-utils 

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-protocol-release#37]
Turns out 3rd party dev encountered a regression after upgrading his dependencies to 1.4.14. This was due to the efficiency of the code that was simply resolved by inlining affecting function. Repeat the steps from old research here https://github.com/casper-network/Governance/issues/74 and find a **new value**, or ensure that the current value is safe, and we need to ensure that documentation for developers has recommendation regarding efficient code.

**Comment by mpapierski** [comment]
Closing .14 is pending activation on integration network which means we have these changes already cc @sacherjj

**Comment by mpapierski** [comment]
Closing .14 is pending activation on integration network which means we have these changes already cc @sacherjj

**Comment by mpapierski** [comment]
Closing .14 is pending activation on integration network which means we have these changes already cc @sacherjj

**Comment by RitaMAllenCA** [comment]
trying to get this to update in the PM tool
